### PR TITLE
fixed overlapping buttons

### PR DESCRIPTION
**Pull request by Captn138**
The 'Dock' and 'Gyms' buttons were overlapping. I moved the 'Gyms' button 20px on the right to fix it.

### CODE REVIEW

**Comment by Ephenia** [comment]
Before:
image

After:
image

😮

**Comment by Captn138** [comment]
Ah I see, I'm gonna check what's wrong. Thank you for the feedback, you can close the PR. :)

**Comment by Captn138** [comment]
Fun fact: I don't have the 'Dungeons' button. Where does it come from?

**Comment by sdkyron** [comment]
Same, where is it ? :D

**Comment by Ephenia** [comment]
👀

**Pull request closed without merging**
