### PR TITLE
New Auto Dungeon mode + misc fixes

### LINKED ISSUE #75: [Feature Request] Auto Dungeon Chest Farm Mode
Would it be possible to add a 3rd option for Auto Dungeon? Currently there are full clear and boss rush. It would be nice to have an option for getting all the chests, then killing boss, while avoiding as many other fights as possible.

### LINKED ISSUE #140: [Feature request] Autodungeon: Treasure hunt mode
Mode that works as follows:  

1. Keep uncovering tiles, but do not activate any dungeon chest, boss battle, or entrance. If the Flash buff is active, prioritize dungeon chest tiles, then boss and empty tiles, then enemy tiles
2. Once enough chests are revealed (`floor(dungeon size / 3)`), go directly to uncovered chest tiles and activate them. This should reveal all other chest tiles
3. Beeline towards other chest tiles (with the previous priorization of tiles) and activate them until `floor(dungeon size / 2)` chests are activated. This should reveal all tiles on the map
4. If there are chest tiles that are blocked off by enemy tiles or if the boss tile is blocked off by enemy tiles, prioritize those enemy tiles first
5. Activate all remaining chest tiles
6. Activate the boss tile

The goal is to get all the treasure and beat the dungeon as fast as possible, meaning with lowest enemy health and fewest battles

### LINKED ISSUE #197: [Feature Request] Enhanced Auto Clicker - Item mode
Other than Farm Mode or Boss Rusher, I feel that there one more mode. It's sort of a hybrid of the two modes. 

It pick up all the chests then rush to the boss instead of fighting all the enemies.

### LINKED ISSUE #353: Pokeclicker installs to %localappdata%, not %appdata% on Windows 11
Unsure if this applies for older versions of Windows, but the [readme](https://github.com/Ephenia/Pokeclicker-Scripts/tree/master/desktop) states that it should install to %appdata% which is incorrect.

### LINKED ISSUE #354: Errors/bugs in AutoSafariZone and DebugCheatTools userscripts caused by v.0.10.16
AutoSafariZone didn't work at all in Bug Catching Contest in Johto, nor in Great Marsh in Sinnoh.

Burn, Chill, Shock and Douse Genesect drives (four new held items) are missing from Held Items tab in DebugCheatTools. 
Wishing Piece is missing from DebugCheatTools too, but I'm not sure if it's a bug or a feature.

### LINKED ISSUE #358: Auto Safari not working for Bug Catching Contest in Johto
Hello!

There is a new Safari Zone in Johto since the last update, however the current script for auto Safari doesn't seem to work properly. Once the safari/contest is over, it sends you back on the map, doesn't do the safari on repeat, and the script gets turned off. It seems to work properly once you're inside the safari however (after you paid the entrance fee, but not on the "entrance screen").

### PR DESCRIPTION
**Pull request by umbralOptimatum**
- Enhanced Auto Clicker
  - Auto Dungeon now has separate fights and chests modes
    - Open all chests without fighting every enemy or vice versa
    - New setting to open rare chests when chests mode is off
  - Rewrote script to be a class and have fewer global variables cluttering things up
  - Closes #75, closes #140, closes #197
- Additional Visual Settings
  - Fixed the dock/gym/dungeon menus allowing some sequence breaking
- Auto Safari Zone
  - Now enabled in Johto's National Park and Sinnoh's Great Marsh
    - In National Park will default to highest-average-token encounter type
  - Improved prioritization between land and water encounters
  - Closes #354, closes #358
- Scripts with their own settings menus now display in a consistent alphabetical order
- Fixed a couple rare desktop issues
- Readme updates
  - Closes #353

### CODE REVIEW

**Comment by elrandira** [comment]
I tried parts of your script and when I activate chest mode, my character stay stuck in the bottom left corner a dungeon.

Here's what I did (on my new computer so fresh install):

- installed tampermonkey
- installed additional visual settings, auto battle frontier, catch filter fantasia, catch speed adjuster, enhanced auto clicker, enhanced auto hatchery scripts
- updated to additional visual settings and enhanced auto clicker scripts from your repo (and only those)

image

as soon as I deactivate the chest mod, the character goes back on its cleaning route.

**Comment by elrandira** [comment]
here's the console log:
image

line 663 of [enhancedautoclicker.user.js](https://github.com/Ephenia/Pokeclicker-Scripts/pull/352/files#diff-24ae160c85af4354613c95b5440cfd47a29f713425ede185e02137d22352e474)

**Comment by elrandira** [comment]
I have some graphical issues a well:
image

**Comment by elrandira** [comment]
script is not loading anymore :p

image

**Comment by elrandira** [comment]
I can know load the script and the chest mode is working.

but I have another issue.. the selection of the chest doesn't work:
image

**Comment by elrandira** [comment]
works like a charm. thanks for the PR.

**Comment by Ephenia** [comment]
Approved, apologies for the delay.

**Comment by lnlyssg** [comment]
Seems like there are issues with the Safari script as per #364

**Pull request merged**
