### PR TITLE
Feature: Option to automatically add Rich Mulch before harvesting

### PR DESCRIPTION
**Pull request by Rocail**
Add an option to automatically add Rich Mulch right before Auto-Harvesting.
It's usefull when you farm berries that takes more than 5 min to harvest.
Feel free to take a look o/

### CODE REVIEW

**Comment by Ephenia** [comment]
A selection for the mulch to use would likely be a better idea with this.

This isn't something I would really add specifically, I mean just for 1 specific mulch and favoring it.

**Comment by Rocail** [comment]
Hmm, but there is no point adding Boost, Surprise or Freezing mulch that way.
It could be nice to automatically renew these mulches tho, but it sounds more like a rework of the AutoMulch rather than a brand new feature, don't you think ?

**Comment by Ephenia** [comment]
Well, yeah, that's just more ideally what I'd like.

I don't care so much about there being a point or not, and the practicality of it. Design wise, I just think it's cleaner, having options.

It's the same thing with, say, how I have Auto Small Restores currently in `EnhancedAutoMining` as an example. I would be implementing an option to rework it to be auto purchasing Super and Hyper Restores as well (as cost inefficient as they would be). That's if I'm ever bothering to rework it.

**Comment by Ephenia** [comment]
I'd also like to add to this in case anyone is wondering or unaware (as I know I have readers who like to read), but the future plans for `SimpleAutoFarmer` is to make it `EnhancedAutoFarmer`. It's really the only script that is in need of a major revamp and has plans to undergo a name change.

And yes, while I do always appreciate improvements and I'm open to ideas, I'm just more keen on my planning or just like what I'd like to see. While I could add this, if it's coming down to me changing things later, this will just end up getting removed/replaced anyway. Not that it's bad and I'm definitely not saying such thing, it's obviously a good addition to what is known as `SimpleAutoFarmer` now, but it's redundant to what I envision for `EnhancedAutoFarmer` having for features. That's really the next step where I'd like to see this script going. 

Also, I really haven't touched this script since I made it at the beginning of the project, and I still don't think that I have any plans to do anything with it anytime soon due to lack of motivation for even being interested enough in the Farm (I'll be honest it's not my personal favorite feature of the game compared to other things). I've been more inclined to just want to create new and innovative things like my recently released scripts. It's really the only true way I'm keeping my own self interested in this project, is to really just do things that I'd like to do at this point. With that being said, I could foresee someone else taking up the challenge of tackling a take on `EnhancedAutoFarmer` before I ever get around to it.

**Comment by Rocail** [comment]
Sure, no problem, it's your project ! That's just a feature I used when I did all the mutations and stuff.
I'll keep working a bit on farming scripts (Currently working on the mutations, with freeze mulch & presets), if you want to discuss about the revamp or anything I'm open to it, else I'll just keep doing my things ^^

**Pull request closed without merging**
