### PR TITLE
Enhanced Auto Farmer (added replant button)

### PR DESCRIPTION
**Pull request by davide-lugli**
Adapted from https://github.com/perkasthor solution posted at https://github.com/Ephenia/Pokeclicker-Scripts/issues/206

### CODE REVIEW

**Comment by Ybanca** [comment]
When will this be added to the script?

**Comment by luisinho7** [comment]
since this seems to be stuck in insuficient votes, is there any way to use that right now despite the fact it hasn't been officially added to the main mod thing?

**Comment by elrandira** [comment]
if you play on computer and use Tampermonkey then yes:
Just go to Files Changes > reach simpleautofarmer.user.js > ... (on the right) > view file > raw
Tampermonkey will open a new page and propose you to install the script

**Comment by luisinho7** [comment]
> if you play on computer and use Tampermonkey then yes: Just go to Files Changes > reach simpleautofarmer.user.js > ... (on the right) > view file > raw Tampermonkey will open a new page and propose you to install the script if you have already a file with the same name installed.

well i play on computer, but the client version, but i guess if it only works in the online one, i could use it to get the berries and then go back

still, thanks

**Comment by luisinho7** [comment]
> With the current version of the desktop script manager, if you download the updated script from this PR and put it in the custom scripts folder with the same name, it should override the old version. Or so the instructions say.

i'm sorry, but... _what_
first of all, i know that the main page mentions a script manager but i very much do not have the script manager despite everything else working
second of all, folder??? what... what folder??? what do you mean folder? am i supposed to somehow open the .asar file and put it inside? cause that's the only possibility i'm getting from this and i have no clue of how to do that

**Comment by luisinho7** [comment]
ah, i see the problem, the .asar was placed in AppData\Local\Programs\pokeclicker-desktop\resources, but the folder where this goes is AppData\Roaming\pokeclicker-desktop\custom-scripts, which is... completely displaced, but at least it works now

**Comment by Ephenia** [comment]
Approved, we'll get this in.

**Pull request merged**
