### PR TITLE
Fix dungeon scan on v0.9.18

### LINKED ISSUE #222: [BUG] Auto dungeon do not work
image

### PR DESCRIPTION
**Pull request by drillskibo**
Closes #222

### CODE REVIEW

**Comment by gaza9422** [comment]
how can i use the fix as hasnt got an install?

**Comment by Kaias26** [comment]
wait, that wont fix anaything, you'll get rid of the error, but the script wont work anyway.
now dungeonBoard is tridimensional (z, x, y), if you check dungeonBoard.length, it will return 1 or 2 (the depth of the dungeon) instead of x axis.

in the end, every functions using dungeonBoard need to be fixed and need to check the depth of the dungeon.

**Comment by Kaias26** [comment]
okay, a quick but ugly way to fix, is updating the line 355 with :
` var dungeonBoard = DungeonRunner.map.board()[DungeonRunner.map.playerPosition().floor];`

but it wont be enough to fix new dungeons with ladders, cause it need a bigger update to actually search and climb the tile...

**Comment by Kaias26** [comment]
Since the update, some dungeons have severall level and we can climb with a ladder.
So, instead of having two arrays, for axis X and Y, the DungeonRunner.map.board() array that you use to wander, scan... contain a third level : the Z axis.

meaning, if you try to get the .type of the tile, you cant use dungeonBoard[ i ] [ j ] anymore, you need to use dungeonBoard[ floorlevel ][ i ][ j ].

You can easily found the currentFloorlevel with : DungeonRunner.map.playerPosition().floor.

Instead of updating every functions with floor level, i've tried to change the var dungeonBoard and that work well :)

the other problem is now to update the wander function to detect and use the ladder tile....

**Comment by drillskibo** [comment]
Oh alright I didn't see the whole ladder thing...
It fixed the issue on my end but only on a one-floor basis, technically.
Now that @Ephenia is aware of the issue, maybe we'll get a more precise reaction to the update ?

**Comment by drillskibo** [comment]
Closed since #224 was merged.

**Pull request closed without merging**
